services:
  backend:
    build: .
    container_name: hosptial-backend

    ports:
      - "8080:8080"
    
    env_file:
      - .env
    
    depends_on:
      - postgres
      - redis
    
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: hospital-postgres

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hospital-redis

    ports:
      - "6379:6379"

    restart: unless-stopped

volumes:
  postgres_data: